In [1]:
import pandas as pd
from Univariate import Univariate
import numpy as np

In [2]:
dataSet = pd.read_csv('Placement.csv')

In [3]:
dataSet = dataSet.drop(labels = 'sl_no', axis=1)

In [4]:
quan,qual = Univariate.SplitDataSet(dataSet)

In [5]:
Univariate.FrequencyTabel('ssc_p', dataSet)

     Unique_values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            52.00          9            0.087379  0.378641
4            73.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           80.60          1            0.009709  2.048544
99           65.20          1            0.009709  2.058252
100          80.40          1            0.009709  2.067961
101          59.96          1            0.009709  2.077670
102          78.50          1            0.009709  2.087379

[103 rows x 4 columns]

In [6]:
descriptive = Univariate.Descriptive(quan, dataSet)

In [7]:
lesser,greater = Univariate.OutLier(quan, descriptive)

In [8]:
descriptive, lesser, greater =  Univariate.ReplaceOutlier(lesser, greater, dataSet, descriptive, quan)

C:\Users\REVANTH KUMAR\Desktop\college\Artificial intellgence\4.Data Science\2.central tendency\Univariate.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataSet[columns][dataSet[columns] < descriptive[columns]['Lesser']] = descriptive[columns]['Lesser']
C:\Users\REVANTH KUMAR\Desktop\college\Artificial intellgence\4.Data Science\2.central tendency\Univariate.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataSet[columns][dataSet[columns] > descriptive[columns]['Greater']] = descriptive[columns]['Greater']

In [9]:
descriptive

             ssc_p      hsc_p   degree_p   etest_p     mba_p    salary
Mean       67.3034    66.3347    66.3586   72.1006   62.2782    277649
Median          67         65         66        71        62    265000
Mode            62         63         65        60      56.7    300000
0%           40.89      42.75         50        50     51.21       NaN
25%           60.6       60.9         61        60    57.945    240000
50%             67         65         66        71        62    265000
75%           75.7         73         72      83.5    66.255    300000
99%             87     91.129      83.86        97   76.1142       NaN
100%          89.4      91.15       88.5        98     77.89    390000
IQR           15.1       12.1         11      23.5      8.31     60000
1.5rules     22.65      18.15       16.5     35.25    12.465     90000
Lesser       37.95      42.75       44.5     24.75     45.48    150000
Greater      98.35      91.15       88.5    118.75     78.72    390000
Min          40.89      42.75         50        50     51.21    200000
Max           89.4      91.15       88.5        98     77.89    390000
skewness -0.132649   0.162611   0.204164  0.282308  0.313576    0.8067
kurtosis  -0.60751  0.0869008 -0.0974897  -1.08858 -0.470723 -0.239837

In [10]:
lesser

[]

In [11]:
greater

[]